batch_size_per_device: 1
eval_steps: 100
gradient_accumulation: 1
max_epochs: 100
max_grad_norm: null
max_grad_value: null
max_length: 512
max_updates: 100000
model_name: model_name_or_path
num_dp_devices: 1
num_tp_devices: 1
patience: 10
save_dir: /path/to/save
save_steps: 1
seed: 42
override: false
reset_status: false
keep_last: null
keep_best: 10

hydra:
  output_subdir: null
  run:
    dir: .

default:
  - _self_
  - optimizer: optimizer name
  - dataset: dataset name
